### ISSUE TITLE
Move vendors dependency folder to a dependency manager

### ISSUE THREAD

**Issue by 0aps** [Nodrix/Anxeb#1]
Team, 
   Currently we have a vendors folder in the library structure. I propose moving front-end dependency to a dependency manager (be npm or bower).

Regards
A

**Comment by ingerosario** [comment]
After commit 501abd85551982f5f42fe88b9d1ebba946a9c294 (v0.1.5) you can choose to ignore internal vendors by writing in the project base head element `{{> anxeb}}`, this will **ONLY** include _init_, _middleware_ and _controllers_ _scripts_. 

In case you want to fragment each Anxeb internal scripts, then you can do the following:
```
{{> anxeb.init}}
{{> anxeb.middleware}}
{{> anxeb.vendors}}
{{> anxeb.controllers}}
```
Also, if you want to set all Anxeb scripts in one step, including vendors, please use: 
```
{{> anxeb.all}}
``` 

This approach will let the developer use third party dependency managers such as Bower.
